version: 2.1

parameters:
  project-folder:
    type: string
    default: "src/Heijden.Dns/"

  csproj-file:
    type: string
    default: "Heijden.Dns.csproj"

  sonar-project:
    type: string
    default: "Lansweeper_Lansweeper.Heijden.Dns"

  git-primary-branch:
    type: string
    default: "master"

executors:
  node:
    docker:
      - image: circleci/node:12

orbs:
  win: circleci/windows@2.2.0
  sonar-check: lansweeper/sonar@0.0.6

commands:
  nuget-prepare:
    description: "generate nuget.config file to pull in (and publish) nuget dependencies "
    steps:
      - run:
          name: Create local nuget config file
          command: |
            $xml = "<?xml version='1.0' encoding='utf-8'?>
            <configuration>
              <packageSources>
                <add key='github' value='https://nuget.pkg.github.com/Lansweeper/index.json' />
              </packageSources>
              <packageSourceCredentials>
                <github>
                  <add key='Username' value='$env:GITHUB_USER' />
                  <add key='ClearTextPassword' value='$env:GITHUB_TOKEN' />
                </github>
              </packageSourceCredentials>
            </configuration>"
            Out-File -FilePath nuget.config -InputObject $xml -Encoding ASCII

  install-deps:
    description: "Install and cache dependencies"
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            - << pipeline.parameters.project-folder >>-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: << pipeline.parameters.project-folder >>-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - nuget-prepare
      - run:
          name: Install SonarScanner for MSBuild .NET Core Global Tool
          command: dotnet tool install --global dotnet-sonarscanner
      - run:
          name: Start SonarScanner
          command: dotnet sonarscanner begin /k:"<< pipeline.parameters.sonar-project >>" /d:sonar.verbose=true /o:"lansweeper" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$Env:SONAR_TOKEN /d:sonar.language="cs"
      - run: dotnet build << pipeline.parameters.project-folder >><< pipeline.parameters.csproj-file >> --configuration Release
      - run:
          name: Upload SonarScanner results
          command: dotnet sonarscanner end /d:sonar.login=$Env:SONAR_TOKEN

      - persist_to_workspace:
          root: .
          paths:
            - .

  validate-sonar:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - sonar-check/get_sonar_status:
          report_file: "/home/circleci/project/.sonarqube/out/.sonar/report-task.txt"

  release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: git config user.email "development@lansweeper.com"
      - run: git config user.name "circleCI-automated-commit"
      - install-deps
      - run:
          name: install dotnet SDK
          command: |
            wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update; \
            sudo apt-get install -y apt-transport-https && \
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-5.0
      - run:
          name: Increase version with semantic-release
          command: yarn run release
      - persist_to_workspace:
          root: .
          paths:
            - .

#  example-push-dependency:
#    docker:
#      - image: circleci/buildpack-deps
#    description: Update nuget version in https://github.com/Lansweeper/TARGET
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: push updated nuget version to TARGET
#          command: |
#            VERSION=${CIRCLE_TAG#"v"}
#            echo $VERSION
#              curl \
#                -X POST \
#                -H "Circle-Token: $CIRCLE_TOKEN" \
#                -H "Content-Type: application/json" \
#                https://circleci.com/api/v2/project/github/Lansweeper/TARGET/pipeline \
#                -d "{\"parameters\": { \"release-new-sync-version\": true,  \"version\": \"$VERSION\" } }"

workflows:
  version: 2

  ci_on_pr:
    jobs:
      - build:
          context:
            - lec-github-packages-rw
            - SonarCloud
          filters:
            branches:
              ignore: << pipeline.parameters.git-primary-branch >>

      - validate-sonar:
          context: SonarCloud
          requires:
            - build
          filters:
            branches:
              ignore: << pipeline.parameters.git-primary-branch >>

  ci_and_release_primary_branch:
    jobs:
      - build:
          context:
            - lec-github-packages-rw
            - SonarCloud
          filters:
            branches:
              only: << pipeline.parameters.git-primary-branch >>

      - release:
          context:
            - lec-github-packages-rw
          requires:
            - build
          filters:
            branches:
              only: << pipeline.parameters.git-primary-branch >>

#  cd_on_release:
#    jobs:
#      - example-push-dependency:
#          context:
#            - lec-circleci-release
#          filters:
#            # ignore any commit on any branch by default
#            branches:
#              ignore: /.*/
#            # only act on version tags
#            tags:
#              only: /^v[0-9]+(\.[0-9]+)*$/